# Site settings
title: Anna's Blog
SEOTitle: No.71 Anna and Ray
header-img: img/post-bg-index1.jpg
email: una.tong@msn.com
description: "Every failure is leading towards success."
keyword: "Anna, Ray, Java, Life, Python"
url: "https://yaegumoanna.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/flyingwzb/flyingwzb.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我就想试试。"
sidebar-avatar: /img/s2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
#weibo_username:     xxxxx
zhihu_username:     Anna童
github_username:    yaegumoanna
# facebook_username:  username
# jianshu_username:   jianshu_id
xiaohongshu_username:   Anna小姐


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: disqus_YwLKfzIdDf

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 1e8841f0a5b06f0bf45f                           #生成的clientID
  clientSecret: 762ffbea94fd6c47f57d6be3dfeb8b42613586e8    #生成的clientSecret
  repo: yaegumoanna.github.io    #仓库名称
  owner: yaegumoanna    #github用户名
  admin: yaegumoanna
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-137811562-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true





# 支付宝、微信打赏二维码
alipay_qr_img: ''
wechat_qr_img: ''
